name: Cypress GitHub CI
on: [push]

jobs:
  cypress-run:
    name: E2E on Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: cypress-io/github-action@v5.0.8
        with:
          runTests: cypress run --browser chrome